src/Westess/RFS/Bundle/AppBundle/Entity/AccommodationType.php
<?php

namespace Westess\RFS\Bundle\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\ExclusionPolicy;

/**
 * AccommodationType
 * @ExclusionPolicy("all")
 */
class AccommodationType
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     * @Expose
     * @Type("string")
     */
    private $name;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return AccommodationType
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
}

src/Westess/RFS/Bundle/AppBundle/Entity/Photo.php
<?php

namespace Westess\RFS\Bundle\AppBundle\Entity;

use Westess\RFS\Bundle\AppBundle\Resources\S3;
use Aws\ConfigService\Exception\ConfigServiceException;
use Aws\S3\S3Client;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\ExclusionPolicy;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Photo
 * @ExclusionPolicy("all")
 */
class Photo
{
    /**
     * @var integer
     * @Expose
     * @Type("integer")
     */
    private $id;

    /**
     * @var boolean
     */
    private $visible;

    /**
     * @var \Westess\RFS\Bundle\AppBundle\Entity\Accommodation
     */
    private $accommodation;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set visible
     *
     * @param boolean $visible
     * @return Photo
     */
    public function setVisible($visible)
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * Get visible
     *
     * @return boolean
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Set accommodation
     *
     * @param \Westess\RFS\Bundle\AppBundle\Entity\Accommodation $accommodation
     * @return Photo
     */
    public function setAccommodation(\Westess\RFS\Bundle\AppBundle\Entity\Accommodation $accommodation = null)
    {
        $this->accommodation = $accommodation;

        return $this;
    }

    /**
     * Get accommodation
     *
     * @return \Westess\RFS\Bundle\AppBundle\Entity\Accommodation
     */
    public function getAccommodation()
    {
        return $this->accommodation;
    }

    private $temp;
    private static $uploadRootDir = 'uploads/images/accommodation';

    /**
     * @Assert\File(maxSize="10M")
     */
    private $file;

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (is_file($this->getAppPath())) {
            // store the old name to delete after the update
            $this->temp = $this->getAppPath();
        }
    }

    /**
     * @ORM\PrePersist()
     *
     */
    public function preUpload()
    {
        if (null == $this->getFile()) {
            throw new \RuntimeException("Trying to upload non-existent file");
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->temp);
            // clear the temp image path
            $this->temp = null;
        }

        //UploadFile move() throws an exception if the file cannot be moved so that the entity is not persisted to the database
        $this->getFile()->move(self::$uploadRootDir . '/' . $this->id, $this->id . '.jpg');

        $this->setFile(null);
    }

    /**
     * @ORM\PreRemove()
     */
    public function storeFilenameForRemove()
    {
        $this->temp = $this->getAppPath();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $this->removeFromBucket();
        if (isset($this->temp)) {
            unlink($this->temp);
        }
    }

    public function getFileRootPath()
    {
        return null === $this->id
            ? null
            : self::$uploadRootDir . '/' . $this->id;
    }

    public function getAppPath()
    {
        return null === $this->id
            ? null
            : self::$uploadRootDir . '/' . $this->id . '/' . $this->id . '.jpg';
    }

    public function getWebPath()
    {
        return null === $this->id
            ? null
            : 'https://s3-eu-west-1.amazonaws.com/rfs-assets' . '/' . self::getAppPath();
    }

    public function saveToBucket()
    {
        putenv("AWS_ACCESS_KEY_ID=AKIAJENPX4O5EIXQXBHQ");
        putenv("AWS_SECRET_ACCESS_KEY=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");
        putenv("S3_BUCKET_NAME=rfs-assets");
        $s3 = new S3(getenv('AWS_ACCESS_KEY_ID'), getenv('AWS_SECRET_ACCESS_KEY'));

        if (!$s3->putObjectFile($this->getAppPath(), getenv("S3_BUCKET_NAME"), $this->getAppPath(), S3::ACL_PUBLIC_READ)) {
            throw new ConfigServiceException('No "S3_BUCKET" config var in found in env!');
        }
    }

    public function removeFromBucket()
    {
        $s3 = new S3(getenv('AWS_ACCESS_KEY_ID'), getenv('AWS_SECRET_ACCESS_KEY'));
        if (!$s3->deleteObject(getenv("S3_BUCKET_NAME"), $this->temp)) {
            throw new ConfigServiceException('No "S3_BUCKET" config var in found in env!');
        }
    }

    public function __toString()
    {
        return strval($this->id);
    }
}

src/Westess/RFS/Bundle/AppBundle/Controller/AccommodationController.php
<?php

namespace Westess\RFS\Bundle\AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use SendGrid\Email;
use Westess\RFS\Bundle\AppBundle\Entity\Accommodation;
use Westess\RFS\Bundle\AppBundle\Form\AccommodationType;
use Westess\RFS\Bundle\AppBundle\Entity\UserAccommodationInterest;

/**
 * Accommodation controller.
 *
 * @Route("/accommodation")
 */
class AccommodationController extends Controller
{


  /**
   * @Route("/favourite/{id}")
   */
   function accommodationFavouriteAction(Request $request, $id)
   {
     if (!$this->get('security.authorization_checker')->isGranted('ROLE_USER')) {
         $session = $request->getSession();
         $session->getFlashBag()->add('info', 'You must be logged in to use this feature');
         throw $this->createAccessDeniedException();
     }
     $em = $this->getDoctrine()->getManager();

     $user= $this->getUser();
     $accommodation = $em->getRepository("RFSAppBundle:Accommodation")->findOneById($id);

     //check if a favourite already exists. if not create one, otherwise delete it.
     $uaInterestPossible = $em->getRepository("RFSAppBundle:UserAccommodationInterest")->findOneBy(array("user" => $user, "accommodation" => $accommodation));
     if($uaInterestPossible == NULL)
     {
       $uaInterest = new UserAccommodationInterest();

       $uaInterest->setUser($user);
       $uaInterest->setAccommodation($accommodation);

       $em->persist($uaInterest);
       $em->flush();
       return new Response("t");
     }
     else
     {
        $em->remove($uaInterestPossible);
        $em->flush();
        return new Response("f");
     }
   }

   /**
    * @Route("/favourite/{id}/readonly")
    */
    function accommodationFavouriteReadOnlyAction(Request $request, $id)
    {
      if (!$this->get('security.authorization_checker')->isGranted('ROLE_USER')) {
          $session = $request->getSession();
          $session->getFlashBag()->add('info', 'You must be logged in to use this feature');
          throw $this->createAccessDeniedException();
      }
      $em = $this->getDoctrine()->getManager();

      $user = $this->getUser();
      $accommodation = $em->getRepository("RFSAppBundle:Accommodation")->findOneById($id);

      //check if a favourite exists return 't' if it does, 'f' is it does not.
      $uaInterest = $em->getRepository("RFSAppBundle:UserAccommodationInterest")->findOneBy(array("user" => $user, "accommodation" => $accommodation));
      if($uaInterest == NULL)
      {
        return new Response("f");
      }
      else
      {
          return new Response("t");
      }
    }

    /**
     * Lists all Accommodation entities.
     *
     * @Route("/", name="accommodation")
     * @Method("GET")
     * @Template("RFSAppBundle:Accommodation:index.html.twig")
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('RFSAppBundle:Accommodation')->findAll();

        $paginator = $this->get('knp_paginator');
        $entities = $paginator->paginate(
            $entities,
            $request->query->get('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return array('entities' => $entities);
    }

    /**
     * @Route("/list/{name}", name="my_accommodations")
     * @Template("RFSAppBundle:Accommodation:index-user.html.twig")
     */
    public function myPropertyAction()
    {
        $this->denyAccessUnlessGranted('ROLE_LANDLORD', null, 'Unauthorized access');

        $user = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository('RFSAppBundle:Accommodation')->createQueryBuilder('a');
        $accommodations = $qb->where($qb->expr()->eq('a.user', ':user'))
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
        return array('entities' => $accommodations);
    }


    /**
     * Creates a new Accommodation entity.
     *
     * @Route("/", name="accommodation_create")
     * @Method("POST")
     * @Template("RFSAppBundle:Accommodation:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_LANDLORD', null, 'Unauthorized access');

        $entity = new Accommodation();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $user = $this->getUser();
            $entity->setUser($user);

            $em->persist($entity);
            $em->flush();

            $photo = $entity->getMainPhoto();
            $photo->setAccommodation($entity);

            foreach ($entity->getPhotos() as $photo) {
                $photo->setAccommodation($entity);
            }

            foreach ($entity->getFeatures() as $feature) {
                $feature->setAccommodation($entity);
            }

            $entity->setViewCount(0);

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('accommodation_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Accommodation entity.
     *
     * @param Accommodation $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Accommodation $entity)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(new AccommodationType($em), $entity, array(
            'action' => $this->generateUrl('accommodation_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Accommodation entity.
     *
     * @Route("/new", name="accommodation_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $this->denyAccessUnlessGranted('ROLE_LANDLORD', null, 'Unauthorized access');

        $entity = new Accommodation();
        $form = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Finds and displays a Accommodation entity.
     *
     * @Route("/{id}", name="accommodation_show")
     * @Method("GET")
     * @Template("RFSAppBundle:Accommodation:show.html.twig")
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('RFSAppBundle:Accommodation')->find($id);

        $viewCount = $entity->getViewCount();
        $entity->setViewCount($viewCount + 1);

        $em->persist($entity);
        $em->flush();

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Accommodation entity.');
        }

        //generate list of users who favourited this accommodation
        if ($this->get('security.authorization_checker')->isGranted('ROLE_USER')){
          $query = $em->createQueryBuilder();
          $userFavourites = $query
              ->select(array("u"))
              ->from("RFSAppBundle:UserAccommodationInterest", "u")
              ->where($query->expr()->neq("u.user", ":thisUser"))
              ->setParameter("thisUser", $this->getUser())
              ->getQuery()->getResult();
          return array('accommodation' => $entity, 'userFavourites' => $userFavourites);
         }

        return array('accommodation' => $entity);
    }

    /**
     * Displays a form to edit an existing Accommodation entity.
     *
     * @Route("/{id}/edit", name="accommodation_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $this->denyAccessUnlessGranted('ROLE_LANDLORD', null, 'Unauthorized access');

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('RFSAppBundle:Accommodation')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Accommodation entity.');
        }

        if ($this->getUser()->getId() != $entity->getUser()->getId()) {
            $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'Unauthorized access');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a form to edit a Accommodation entity.
     *
     * @param Accommodation $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Accommodation $entity)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(new AccommodationType($em), $entity, array(
            'action' => $this->generateUrl('accommodation_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * Edits an existing Accommodation entity.
     *
     * @Route("/{id}", name="accommodation_update")
     * @Method("PUT")
     * @Template("RFSAppBundle:Accommodation:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {

src/Westess/RFS/Bundle/AppBundle/Resources/views/Accommodation/edit.html.twig
{% extends 'RFSAppBundle::base.html.twig' %}
{% block page_styles %}
    <link rel="stylesheet" type="text/css" href="{{ asset('stylesheets/jasny.min.css') }}"
          media="screen, projection">
    <style type="text/css">
        #photosModal img {
            height: 200px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="block-content block-content-small-padding">
        <div class="block-content-inner">
            <h1 class="center">Edit accommodation</h1>
            <span class="record_actions">
                    <a class="btn" href="{{ path('accommodation') }}"><i class="fa fa-list-ul"></i>&nbsp;Back to
                        list</a>
                {{ form(delete_form) }}
            </span>

            <div class="box col-sm-8 col-sm-offset-2">

                {% if edit_form is defined %}
                    {% set form = edit_form %}
                    {{ form_start(form, {'attr': {'id': 'accommodation-form'}}) }}
                    <div class="text-danger text-center"><h5 class="center">{{ form_errors(form) }}</h5>
                    </div>
                    <div class="form-group">{{ form_row(form.fullAddress, {'attr':{'class':'form-control', 'placeholder':'Enter address'}}) }}</div>
                    <div class="form-group">
                        <div class="form-control" id="map" style="height: 250px"></div>
                    </div>
                    <div class="form-group">{{ form_row(form.description, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.accommodationType, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.pricePlan, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.price, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.contractLength, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.bedrooms, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.isEnSuite, {'attr':{'class':'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.publishStartDate, {'attr':{'class':'form-control', 'value':'now'|date('Y-m-d'), 'min':'now'|date('Y-m-d')}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.publishEndDate, {'attr':{'class':'form-control', 'value':'now'|date('Y-m-d'), 'min':'now'|date('Y-m-d')}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.mainPhoto, {'attr':{'class':'form-control', 'placeholder':'Select main photo'}}) }}</div>
                    <div class="form-group col-md-6">
                        <div><label>More info</label></div>

                        <a class="btn btn-sm" data-toggle="modal" data-target="#featuresModal">
                            <i class="fa fa-arrows-alt"></i> Features
                        </a>

                        <a class="btn btn-sm" data-toggle="modal" data-target="#photosModal">
                            <i class="fa fa-arrows-alt"></i> Photos
                        </a>

                        <div class="modal fade" id="featuresModal" tabindex="-1" role="dialog"
                             aria-labelledby="featuresModalLabel"
                             aria-hidden="true" style="margin-top: 90px">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="featuresModalLabel">Features
                                            <a class="close btn pull-right"
                                               data-dismiss="modal"
                                               aria-label="Close">
                                                <i class="fa fa-times" aria-hidden="true"></i></a></h4>
                                    </div>
                                    <div class="modal-body">
                                        <ul class="features"
                                            data-prototype="{{ form_widget(form.features.vars.prototype)|e }}">
                                            {# iterate over each existing feature and render its name #}
                                            {% for feature in form.features %}
                                                <li>{{ form_row(feature.featureType) }}</li>
                                                <hr>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="modal-footer">
                                        <span class="error">{{ form_errors(form.features) }}</span>
                                        <button id="add-feature-link" class="btn btn-sm"><i class="fa fa-plus"></i> Add
                                        </button>
                                        <button type="button" class="btn btn-sm" data-dismiss="modal">Done
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="photosModal" tabindex="-1" role="dialog"
                             aria-labelledby="photosModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="photosModalLabel">More photos
                                            <a class="close btn pull-right"
                                               data-dismiss="modal"
                                               aria-label="Close">
                                                <i class="fa fa-times" aria-hidden="true"></i></a></h4>
                                    </div>
                                    <div class="modal-body">
                                        <form id="photos-form" method="POST"
                                              action="{{ path('edit_photos', { 'id': entity.id }) }}"
                                              enctype="multipart/form-data">
                                            <ul class="edit-photos" style="list-style-type: none;">
                                                <li><label>Photos</label></li>
                                                {% for photo in entity.photos %}
                                                    <li>
                                                        <div class="fileinput fileinput-new col-sm-12"
                                                             data-provides="fileinput">
                                                            <div class="fileinput-new thumbnail">
                                                                <img src="{{ asset(photo.webPath) }}"
                                                                     alt="...">
                                                            </div>
                                                            <div class="fileinput-preview fileinput-exists thumbnail"
                                                                 style="max-height: 150px;"></div>
                                                            <div>
                                            <span class="btn btn-default btn-xs btn-file">
                                                <span class="fileinput-new">Select</span>
                                                <span class="fileinput-exists">Change</span>
												<input class="fileinput-filename" value=""
                                                       type="file" id="photos_{{ photo.id }}"
                                                       name="photos[{{ photo.id }}]"
                                                       accept="image/*">
											</span>
                                                                <a href="#"
                                                                   class="btn btn-danger fileinput-exists btn-xs"
                                                                   data-dismiss="fileinput">Reset</a>
                                                            </div>
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            </ul>

                                            <div class="form-group">
                                                <input form="photos-form" type="submit"
                                                       class="btn btn-primary btn-inversed btn-block" value="Update">
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <span class="error"></span>
                                        <button type="button" class="btn btn-sm" data-dismiss="modal">Done</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-md-6">{{ form_row(form.isVisible, {'attr' :{'class' : 'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.publishStartDate, {'attr' :{'class' : 'form-control'}}) }}</div>
                    <div class="form-group col-md-6">{{ form_row(form.publishEndDate, {'attr' :{'class' : 'form-control'}}) }}</div>
                    <div class="form-group col-md-12">{{ form_row(form.submit, {'attr' :{'class' : 'btn btn-primary btn-block'}}) }}</div>
                    {{ form_end(form) }}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}
{% block page_scripts %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
    {% javascripts
    'js/jasny.min.js'
    '@RFSAppBundle/Resources/public/js/accommodation.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    <script type="text/javascript">
        // Update property photos
        $(function () {
            var prototype = '<div class="fileinput fileinput-new col-sm-12" data-provides="fileinput">' +
                    '<div class="fileinput-new thumbnail">' +
                    '<img height="180px" src="http://placehold.it/300x200&text=UAEDXB" alt="..."> ' +
                    '</div>' +
                    '<div class="fileinput-preview fileinput-exists thumbnail" style="max-height: 180px;"></div>' +
                    '<div>' +
                    '<span class="btn btn-default btn-xs btn-file"> ' +
                    '<span class="fileinput-new">Select</span> ' +
                    '<span class="fileinput-exists">Change</span> ' +
                    '<input class="fileinput-filename" value="" ' +
                    'type="file" id="photos___name__" name="photos[__name__]" accept="image/*">' +
                    '</span>' +
                    '<a href="#" class="btn btn-danger fileinput-exists btn-xs" ' +
                    'data-dismiss="fileinput">Reset</a>' +
                    '</div>' +
                    '</div>';

            var index = 0;

            $(document).ready(function () {
                // Get the ul that holds the collection of photos
                $collectionHolder = $('ul.edit-photos');

                // count the current form inputs we have (e.g. 2), use that as the new
                // index when inserting a new item (e.g. 2)
                index = $collectionHolder.find(':input').length;

                for (index++; index <= 4; index++) {

                    // add a new photo forms to make up 4 photos
                    // Replace '__name__' in the prototype's HTML to
                    // instead be a number based on how many items we have
                    var newForm = prototype.replace(/__name__/g, 'new_' + index);

                    // Display the form in the page in an li, before the "Add a photo" link li
                    var $newFormLi = $('<li></li>').append(newForm);
                    $collectionHolder.append($newFormLi);
                }
            });
        });
    </script>
    {% endjavascripts %}
{% endblock %}

src/Westess/RFS/Bundle/AppBundle/Resources/views/Accommodation/index.html.twig
{% extends 'RFSAppBundle::base.html.twig' %}

{% block content %}
    <section class="container">
        <h2>Property list</h2>
        <table class="table table-striped records_list">
            <thead>
            <tr>
                <th>Serial</th>
                <th>Photo</th>
                <th>Address</th>
                <th>Type</th>
                <th>Price <i>
                        <small>£</small>
                    </i></th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for accommodation in entities %}
                {% set price = accommodation.price~(accommodation.pricePlan == 1 ? ' / week' : (accommodation.pricePlan == 2 ? ' / month' : ' / year')) %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>
                        {% if accommodation.mainPhoto %}
                            <img src="{{ asset(accommodation.mainPhoto.webPath) }}"
                                 alt="accommodation photo" width="100">
                        {% else %}
                            <img src="http://placehold.it/100x75&text=UAEDXB" alt=""/>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('accommodation_show', { 'id': accommodation.id }) }}">{{ accommodation.fullAddress[0:25] }}
                            &nbsp;...</a>
                    </td>
                    <td>{{ accommodation.accommodationType.name }}</td>
                    <td>{{ price }}</td>
                    <td>
                        {#Implement user actions#}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="center">
            {{ knp_pagination_render(entities) }}
        </div>
    </section>
{% endblock %}